lib/zoom/actions/webinar.rb, spec/fixtures/webinar/registrant/get.json, spec/lib/zoom/actions/webinar/registrants/get_spec.rb
From: https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/webinarregistrantget
Endpoint: GET /webinars/{webinarId}/registrants/{registrantId}
=> Implement get_webinar_registrant

lib/zoom/constants.rb
Looks like the two of the keys in `USER_CREATE_TYPES` were swapped. I was pretty confused there for a moment until I double checked the zoom docs.
https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usercreate
=> Swaps keys for autoCreate and custCreate

README.md, lib/zoom.rb, lib/zoom/client.rb, lib/zoom/clients/jwt.rb, lib/zoom/clients/oauth.rb, spec/lib/zoom/actions/webinar/create_spec.rb, spec/lib/zoom/client_spec.rb, spec/spec_helper.rb
The Zoom API allows both JWT and OAuth access to the API.  This feature adds an
OAuth client to compliment the existing JWT client.  By default, the JWT client
will be used with creating a client with Zoom.new.   To create an OAuth client,
the client is created directly (Zoom::Clients::OAuth.new).
This commit keeps backwards compatibility with clients created using Zoom.new,
but applications that used the client directly, Zoom::Client.new will be affected.
Changes:
- Make Zoom::Client a base class
- Add Zoom::Clients::JWT and Zoom::Clients::OAuth
- Update readme with client examples
- Move JWT specific code out of Zoom::Client and into Zoom::Clients::JWT
- Add OAuth client specific tests
- Modify one existing spec to use both types of clients
- Re-Enable the zoom/client_spec.rb tests
=> Implement an OAuth client for the Zoom API

lib/zoom/actions/roles.rb
Otherwise we get
```
Request Body should be a valid JSON object.
```
=> Bring back to_json for roles actions

lib/zoom/actions/meeting.rb
Added support for the API [Meeting Registrants Questions Update](https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingregistrantquestionupdate).
=> API for updating questions for registrering a meeting

spec/lib/zoom/client_spec.rb
I found that the test to check the default timeout is failing intermittently when it runs after the next test to set the timeout. 
Fixed it by making the configuration nil at tne end of each test.
=> Fix the intermittent failure for the default timeout test client_spec:17

lib/zoom/error.rb, lib/zoom/utils.rb, spec/lib/zoom/utils_spec.rb
Sadly the authentication error doesn't follow the error code spec https://marketplace.zoom.us/docs/api-reference/error-definitions
The returned hash is: 
```
=> {"code"=>124, "message"=>"Invalid access token."}
```
I refactored the code to take this into account and re enabled the spec for this part of the code
=> Better: raise AuthentificationError on code 124

lib/zoom/clients/oauth.rb, spec/lib/zoom/client_spec.rb
There is a typo in refresh_token preventing the OAuth client from working correctly
=> Fix: Set refresh token on OAuth Client.

lib/zoom/params.rb
Apparently, Ruby 2.7 requires that we require this library explicitly.
Although, it works in irb in Ruby 2.7.
Ruby 2.6 works without it.
Based on a PR I found for another project, it seems this problem also existed
in Ruby 2.2. So who knows.
That PR is here: https://github.com/jnunemaker/httparty/pull/532
=> Fix uninitialized constant SimpleDelegator

lib/zoom/clients/oauth.rb, spec/lib/zoom/client_spec.rb
Added `expires_in`, `expires_at` attributes to `Zoom::Client::OAuth`.
expires_in is included in the Zoom API response,
expires_at is a common attribute for OAuth libraries, and I think it's useful to have it.
=> Add expires_in/expires_at to OAuth client

lib/zoom/clients/oauth.rb, spec/lib/zoom/client_spec.rb
Just a quick note, not sure if you want to include it but if you try and instantiate a client with a refresh token then there will be an error as was mentioned before, which may cause confusion.
=> No need to require auth args if auth_token is included

lib/zoom/actions/webinar.rb
Hi,
This PR adds host_video, meeting_authentication, on_demand and autorecording to the list os permitted settings when creating a webinar.
Thanks.
=> Add host_video, meeting_authentication, on_demand, autorecording to possible settings

lib/zoom/actions/meeting.rb, spec/fixtures/meeting/invitation.json, spec/lib/zoom/actions/meeting/invitation_spec.rb
Provides endpoint for possibility to get a meeting invitation.
Link to the Zoom API documentation: https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetinginvitation
=> Adds possibility to get meeting invitation by :meeting_id

README.md, lib/zoom/client.rb, spec/lib/zoom/client_spec.rb
We're already storing the Zoom app credentials in the client configuration. The changes here use the configuration credentials to build the authorization header auth token instead of loading it from hard-coded environment variables
Also updated the README to remove some older usage docs.
=> Using configuration credentials instead of environment variables

lib/zoom/actions/token.rb, lib/zoom/clients/oauth.rb
To revoke a users access token, make a POST request to `https://zoom.us/oauth/revoke`
https://marketplace.zoom.us/docs/guides/auth/oauth#revoking
Usage
```
zoom_client = Zoom::Client::OAuth.new(access_token: 'xxx')
zoom_client.revoke
```
=> Revoking an Access Token

README.md
```ruby
~/hardbap
11:07 $ gem list | ag zoom
zoom_rb (0.10.0)
~/hardbap
11:07 $ irb
irb(main):001:0> require 'zoom_rb'
Traceback (most recent call last):
LoadError (cannot load such file -- zoom_rb)
irb(main):002:0> require 'zoom'
=> true
```
=> Update Readme with correct require statement

lib/zoom/actions/user.rb
Some of posts requests needs to use `to_json` transform on body to avoid the message `Request Body should be a valid JSON object.`
This is a fix for `user_assistants_create` method.
=> JSON transform to create user assistant

lib/zoom/actions/recording.rb, spec/fixtures/recording/settings/get.json, spec/lib/zoom/actions/recording/settings/get_spec.rb, spec/lib/zoom/actions/recording/settings/update_spec.rb
Hi,
This PR adds support for these two endpoints:
https://marketplace.zoom.us/docs/api-reference/zoom-api/cloud-recording/recordingsettingupdate
https://marketplace.zoom.us/docs/api-reference/zoom-api/cloud-recording/recordingsettingsupdate
Thanks,
Gonzalo.
=> Add webinar recording settings and specs

lib/zoom/actions/user.rb
Allows for meeting_authentication, recording_authentication, and meeting_security fetch from API
=> Add option param to user_settings_get

lib/zoom/actions.rb, lib/zoom/actions/token.rb, spec/lib/zoom/actions_spec.rb
I made an error in my refactor and failed to change the headers for
OAuth requests. This will replace the "base_uri" option with a flag,
"oauth" which will automatically set the base_uri and the headers for
OAuth requests. The only requests that use these are Zoom::Actions::Token.
=> Fix OAuth bug

lib/zoom/actions/recording.rb
meeting_recording_get had wrong endpoint '/meetings/:meeting_id/recordings/settings'
=> fix endpoint for meeting_recording_get

lib/zoom/actions/webinar.rb, spec/fixtures/webinar/create.json
A mistake was made when these keys were originally added. This is not a
"question_answer" boolean but rather a "question_and_answer" hash containing
multiple other variables.
Resolves #393
=> Use correct "question_and_answer" spec

lib/zoom/actions/token.rb, lib/zoom/client.rb, lib/zoom/clients/server_to_server_oauth.rb, spec/lib/zoom/client_spec.rb, spec/spec_helper.rb
Now zoom_rb gem doesn't support ServerToServerOAuth. This PR adds ServerToServerOAuth class. For information view the page: https://marketplace.zoom.us/docs/guides/build/server-to-server-oauth-app/
=> KMP-3232: ServerToServerOAuth client

lib/zoom/actions/webinar.rb, lib/zoom/params.rb, spec/lib/zoom/params_spec.rb
This PR will add a language interpretation option to webinars settings that will allow interpreters to be added on zoom.
=> Let webinars update API accepts language interpretation in settings

lib/zoom/actions.rb, spec/lib/zoom/actions_spec.rb
Now by default extra parameters for DELETE requests are not passed. This PR changes it to pass params in the query string.
=> Query params for delete

lib/zoom/error.rb, lib/zoom/utils.rb, spec/lib/zoom/actions/groups/create_spec.rb, spec/lib/zoom/actions/groups/update_spec.rb, spec/lib/zoom/actions/im/chat/channels/get_spec.rb, spec/lib/zoom/actions/user/update_email_spec.rb, spec/lib/zoom/actions/user/update_status_spec.rb, spec/lib/zoom/utils_spec.rb
It's hard to handle errors generated by the gem in the App which uses it because the errors are too common. There is only Zoom::AuthenticationError and Zoom::Error for any other cases.
This PR improves error generation. The error classes added for common http codes.
https://marketplace.zoom.us/docs/api-reference/error-definitions is used for reference.
=> KMP-3014: improve error generation

lib/zoom/actions/webinar.rb, spec/fixtures/webinar/past_webinars_absentees.json, spec/lib/zoom/actions/webinar/past_webinar_absentees_spec.rb
Added endpoint for past webinar absentees
https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#tag/Webinars/operation/webinarAbsentees
=> Past webinars absentees

lib/zoom/error.rb, spec/lib/zoom/errors_spec.rb
In response to https://github.com/hintmedia/zoom_rb/pull/429#issuecomment-1204148701, need to inherit from `Zoom::Error` to maintain backwards compatibility.
=> Inherit from Zoom::Error

lib/zoom/actions/meeting.rb
Register up to 30 registrants at once for a meeting that requires registration.
=> Batch registrants

lib/zoom/actions/meeting.rb, spec/lib/zoom/actions/meeting/registrants/update_status_spec.rb
Hi! I didn't find a issue with this endpoint. 
It would be nice if it appeared :)
https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#operation/meetingRegistrantStatus
=> Add meeting_registrants_status_update api

Gemfile.lock, lib/zoom/clients/jwt.rb, lib/zoom/version.rb
This will likely be the final version in the 1.x releases. 2.x will remove the JWT client and use the S2SOAuth client as recommended in the zoom docs.
=> Deprecate JWT Client

lib/zoom/actions/report.rb
Both the GET `/report/meetings/{meetingId}/participants` and GET `/report/webinars/{webinarId}/participants` endpoints support the `include_fields` enum to specify loading the `registrant_id` for each participant, so this adds support for that to the gem.
=> Add support for `include_fields` enum parameter

lib/zoom/actions/meeting.rb
Per https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingCreate one can add the `pre_schedule: true` parameter.
Currently we're using v1.1.8 of the app. Ideally we'd love to see this go into v1.1.9.
From the docs: 
> Whether to create a prescheduled meeting via the GSuite app. This only supports the meeting type value of 2 (scheduled meetings) and 3 (recurring meetings with no fixed time).
>
> true - Create a prescheduled meeting.
> false - Create a regular meeting.Default: false
Is there a reason this was omitted other than it's not commonly used?
Thanks!
=> Add pre_schedule as an optional parameter to the meeting_create action

lib/zoom/actions/meeting.rb, spec/lib/zoom/actions/meeting/delete_registrant_spec.rb
Adds a meeting_delete_registrant action per the spec at https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/\#operation/meetingregistrantdelete.
We added this before realizing there was an open PR https://github.com/kyleboe/zoom_rb/pull/465 to do some similar work. We're happy either way.
=> Adds a meeting_delete_registrant action

lib/zoom/actions/user.rb, spec/fixtures/user/zak.json, spec/lib/zoom/actions/user/zak_spec.rb
Adds an action to fetch an user's ZAK token as per spec at https://developers.zoom.us/docs/api/rest/reference/user/methods/#operation/userZak
=> Action to fetch user's ZAK token

lib/zoom/actions/meeting.rb, spec/lib/zoom/actions/meeting/create_spec.rb
Adds the waiting_room parameter (boolean) to meeting_create to enable the [Waiting Room feature](https://support.zoom.us/hc/en-us/articles/115000332726-Waiting-Room).
=> Add waiting_room parameter to meeting_create

lib/zoom/error.rb, lib/zoom/utils.rb, spec/fixtures/error/unauthorized_request.json, spec/lib/zoom/actions/groups/get_spec.rb, spec/lib/zoom/actions/groups/list_spec.rb, spec/lib/zoom/actions/im/chat/channels/get_spec.rb, spec/lib/zoom/actions/im/chat/users/channels/get_spec.rb, spec/lib/zoom/actions/meeting/update_spec.rb, spec/lib/zoom/actions/webinar/create_spec.rb, spec/lib/zoom/actions/webinar/list_spec.rb, spec/lib/zoom/actions/webinar/poll_get_spec.rb, spec/lib/zoom/actions/webinar/polls_list_spec.rb, spec/lib/zoom/utils_spec.rb
At the moment there is a mixup between HTTP error codes and Zoom error codes. That makes it difficult to handle errors properly.
This PR addresses some issues with error mapping and error handling (which also has been described in https://github.com/kyleboe/zoom_rb/issues/464):
- Aligns http error codes to corresponding error classes
- For http error codes check: https://developers.zoom.us/docs/api/rest/error-definitions/
- Map Zoom error attributes to Error type attributes in order to make it easier to check for specific Zoom error codes 
Be aware that this would be a breaking change, because it changes the structur of error messages.
=> Fix error status mapping and improve error handling

lib/zoom/actions/webinar.rb, spec/fixtures/webinar/past_webinars_participants.json, spec/lib/zoom/actions/webinar/past_webinar_participants_spec.rb
This PR adds the past webinar participants action:
https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/listWebinarParticipants
=> Add a past_webinars_participants action

lib/zoom/actions/webinar.rb, spec/lib/zoom/actions/webinar/registrants/delete_spec.rb
This PR adds the webinar registrant delete action:
https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/deleteWebinarRegistrant
=> Add a webinar_registrant_delete action
