kyleboe/zoom_rb

- lib/zoom/actions/webinar.rb
Pretty straight-forward. :smile:
> Allow registrants_confirmation_email setting

- lib/zoom/actions/report.rb
Thanks for the nice gem.  I tried the daily_report call and notice it was not sending the headers
> need to pass request headers

- lib/zoom/actions/user.rb
- spec/fixtures/user/settings_get.json
- spec/lib/zoom/actions/user/settings_get_spec.rb
Implementation and tests for https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usersettings
> Implement GET /users/{userId}/settings

- lib/zoom/actions/recording.rb
- lib/zoom/actions/user.rb
- spec/fixtures/user/recording/list.json
- spec/lib/zoom/actions/user/list_recordings.spec
Hey. Just started to use this and needed to implement user recordings list. Thx
> add user list recordings

- lib/zoom/actions/report.rb
- spec/fixtures/report/meeting.json
- spec/fixtures/report/meeting/participants.json
- spec/lib/zoom/actions/report/meeting_details_report_spec.rb
- spec/lib/zoom/actions/report/meeting_participants_report_spec.rb
Implemented two meeting reports:
- Meeting Detail Report
- Meeting Participants Report
> Add meeting reports

- lib/zoom/actions/meeting.rb
- lib/zoom/actions/metrics.rb
- lib/zoom/actions/recording.rb
- lib/zoom/actions/token.rb
- lib/zoom/actions/webinar.rb
Some syntax cleanup across the actions.
> Cleanup Symbol Array Literal

- lib/zoom/actions/user.rb
- spec/fixtures/user/email_check.json
- spec/lib/zoom/actions/user/email_check_spec.rb
Added user_email_check call, tested locally and seems to work.
> Added user_email_check call

- lib/zoom/actions/report.rb
> Cleanup report methods

- lib/zoom/actions/report.rb
- lib/zoom/actions/roles.rb
#236 needs to be merged first.
Removing non-implemented methods and some cleanup to match api docs.
> Roles tweaks

- lib/zoom/actions/report.rb
- lib/zoom/actions/roles.rb
- lib/zoom/actions/user.rb
- lib/zoom/actions/webinar.rb
- spec/lib/zoom/actions/user/activate_spec.rb
- spec/lib/zoom/actions/user/checkemail_spec.rb
- spec/lib/zoom/actions/user/checkzpk_spec.rb
- spec/lib/zoom/actions/user/deactivate_spec.rb
- spec/lib/zoom/actions/user/email_check_spec.rb
- spec/lib/zoom/actions/user/revoketoken_spec.rb
- spec/lib/zoom/actions/user/updatepassword_spec.rb
Closes #311 
Needs #308 to be merged first.
Mainly renaming and removal of unused files.
> User tweaks

- lib/zoom/actions/account.rb
- spec/lib/zoom/actions/account/get_locked_settings_spec.rb
> Add get locked settings endpoint and specs

- lib/zoom/actions/account.rb
- spec/fixtures/account/managed_domains.json
- spec/lib/zoom/actions/account/managed_domains_spec.rb
> Account managed domains

- lib/zoom/actions/account.rb
- spec/fixtures/account/trusted_domains.json
- spec/lib/zoom/actions/account/trusted_domains_spec.rb
> #61 - Zoom::Actions::Account#account_trusted_domains

- lib/zoom/actions/billing.rb
- spec/fixtures/billing/plans_usage.json
- spec/lib/zoom/actions/billing/plans_usage_spec.rb
closes #70 
@kyleboe Happy Hacktoberfest 🎃  too!
> #70 - Zoom::Actions::Billing#billing_plans_usage

- lib/zoom/actions/sip_audio.rb
- lib/zoom/client.rb
- lib/zoom_rb.rb
- spec/fixtures/account/sip_trunks_get.json
- spec/lib/zoom/actions/sip_audio/get_trunks_spec.rb
> Add get sip audio trunks endpoint and specs

- lib/zoom/actions/user.rb
- spec/lib/zoom/actions/user/settings_update_spec.rb
Adds support for user_settings updates: https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usersettingsupdate
> Adds user_settings_update

- lib/zoom/actions/user.rb
- spec/lib/zoom/actions/user/update_password_spec.rb
Hi,
This PR adds the User Update password endpoint.
> Add endpoint for updating a password

- lib/zoom/actions/groups.rb
- spec/fixtures/error/group_not_exist.json
- spec/fixtures/groups/create.json
- spec/lib/zoom/actions/groups/create_spec.rb
- spec/lib/zoom/actions/groups/update_spec.rb
> #132 - Create a Group, #134 - Update a Group

- lib/zoom/actions.rb
- lib/zoom/actions/token.rb
- lib/zoom/client.rb
- lib/zoom/clients/oauth.rb
- spec/fixtures/token/revoke_token.json
- spec/lib/zoom/actions/token/access_token_spec.rb
- spec/lib/zoom/actions/token/data_compliance_spec.rb
- spec/lib/zoom/actions/token/refresh_token_spec.rb
- spec/lib/zoom/actions/token/revoke_token_spec.rb
- spec/lib/zoom/actions_spec.rb
This PR relates to this issue: https://github.com/hintmedia/zoom_rb/issues/401
> Support for zoom security improvements.

- CHANGELOG.md
- Gemfile.lock
- lib/zoom/version.rb
Add relevant notes to the Changelog.
> Update version to 1.1.0

- lib/zoom/utils.rb
- spec/lib/zoom/utils_spec.rb
> handle http error status

- .gitignore
- lib/zoom/actions/meeting.rb
List users that have registered for a meeting.
> List meeting registrants

- lib/zoom/actions/meeting.rb
- spec/fixtures/meeting/instances.json
- spec/lib/zoom/actions/meeting/get_spec.rb
Hi! This issue fix 
https://github.com/hintmedia/zoom_rb/issues/161
> Add past_meeting_instances api

- lib/zoom/actions/webinar.rb
> webinair settings keys fix

- lib/zoom/actions/report.rb
- lib/zoom/actions/webinar.rb
added get 'webinar_details_report', '/report/webinars/:webinar_id'
> Webinar details report

- lib/zoom/actions/user.rb
Modified user_update to allow custom attributes
> Permit custom attributes for user update

- lib/zoom/actions/meeting.rb
- spec/fixtures/meeting/get_survey.json
- spec/lib/zoom/actions/meeting/get_survey_spec.rb
See docs here:
- https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingSurveyUpdate
- https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingSurveyDelete
- https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingSurveyGet
> Support for Meeting Surveys
